Repository w3c/vc-data-integrity, pull requests merged in 2024-06, with the labels that each got.

#262 Correct draw.io setting for svg generation
  vocab/security/vocabulary.svg
Labels: editorial

#266 Update proof section properties
  index.html
Labels: CR1, normative

#267 Add type annotation to encoding/decoding examples.
  index.html
Labels: CR1, editorial

#265 Update proof set/chain verification algorithm.
  index.html
Labels: CR1, normative

#269 Explain difference between VM in proof and controller document.
  index.html
Labels: CR1, editorial

#271 Add Security Considerations section on Protected Information.
  index.html
Labels: CR1, editorial

#270 Add explanation about proof graphs
  index.html
Labels: CR1, editorial

#273 Clarify that proof purpose and VM relationship should match.
  index.html
Labels: CR1, editorial

#274 Error code update and consolidation
  index.html
Labels: CR1, normative
